package tampilan;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import koneksi.koneksi;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ucok Ranto
 */
public class menu_utama extends javax.swing.JFrame {
private Connection conn = new koneksi().connect();
    /**
     * Creates new form menu_utama
     */
    public menu_utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        m_kasir = new javax.swing.JMenuItem();
        m_pelanggan = new javax.swing.JMenuItem();
        master_barang = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        master_barang1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Pelanggan = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        Barang = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setBackground(new java.awt.Color(255, 51, 51));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setText("WELCOME TO PARAJARAN STORE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jMenu1.setText("Master");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        m_kasir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        m_kasir.setText("Kasir");
        m_kasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_kasirActionPerformed(evt);
            }
        });
        jMenu1.add(m_kasir);

        m_pelanggan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        m_pelanggan.setText("Pelanggan");
        m_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_pelangganActionPerformed(evt);
            }
        });
        jMenu1.add(m_pelanggan);

        master_barang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        master_barang.setText("Barang");
        master_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                master_barangActionPerformed(evt);
            }
        });
        jMenu1.add(master_barang);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Transaksi");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        master_barang1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        master_barang1.setText("Nota");
        master_barang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                master_barang1ActionPerformed(evt);
            }
        });
        jMenu3.add(master_barang1);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Report");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        Pelanggan.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Pelanggan.setText("Pelanggan");
        Pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PelangganActionPerformed(evt);
            }
        });
        jMenu2.add(Pelanggan);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMenuItem1.setText("Kasir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        Barang.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Barang.setText("Barang");
        Barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarangActionPerformed(evt);
            }
        });
        jMenu2.add(Barang);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_pelangganActionPerformed
        Master_Pelanggan p = new Master_Pelanggan();
        p.setVisible(true);
        p.setLocationRelativeTo(null);
    }//GEN-LAST:event_m_pelangganActionPerformed

    private void m_kasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_kasirActionPerformed
        Master_Kasir mk = new Master_Kasir();
        mk.setVisible(true);
        mk.setLocationRelativeTo(null);
    }//GEN-LAST:event_m_kasirActionPerformed

    private void master_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_master_barangActionPerformed
        Master_Barang mb = new Master_Barang();
        mb.setVisible(true);
        mb.setLocationRelativeTo(null);
    }//GEN-LAST:event_master_barangActionPerformed

    private void master_barang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_master_barang1ActionPerformed
        Transaksi_nota frmN = new Transaksi_nota();
        frmN.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_master_barang1ActionPerformed

    private void BarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarangActionPerformed
        try {
            String path = "C://Users//Hype G12//Documents//NetBeansProjects//project_individu-master (u)//project_individu-master//src//Report/barang.jasper";
            HashMap parameter = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path, parameter,conn);
            JasperViewer.viewReport(print, false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"Dokumen Tidak Ada" +ex);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BarangActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            String path = "C://Users//Hype G12//Documents//NetBeansProjects//project_individu-master (u)//project_individu-master//src//Report/kasir"
            + ".jasper";
            HashMap parameter = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path, parameter,conn);
            JasperViewer.viewReport(print, false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"Dokumen Tidak Ada" +ex);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void PelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PelangganActionPerformed
        try {
            String path = "C://Users//Hype G12//Documents//NetBeansProjects//project_individu-master (u)//project_individu-master//src//Report/pelanggan.jasper";
            HashMap parameter = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path, parameter,conn);
            JasperViewer.viewReport(print, false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"Dokumen Tidak Ada" +ex);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_PelangganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                menu_utama frame = new menu_utama();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Barang;
    private javax.swing.JMenuItem Pelanggan;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem m_kasir;
    private javax.swing.JMenuItem m_pelanggan;
    private javax.swing.JMenuItem master_barang;
    private javax.swing.JMenuItem master_barang1;
    // End of variables declaration//GEN-END:variables
}
